### ISSUE TITLE
Problem with debugging in Sdc tutorial.

### ISSUE THREAD

**Issue by m-kru** [AdaCore/gps#101]
I was trying to get trough the GPS tutorial, however I got stuck at debugger. It does not behave as it is described in the tutorial, it does not stop at the exception. The output is as follows:
![image](https://user-images.githubusercontent.com/26227737/82124909-921b9a00-97a2-11ea-9bd1-cf390bda28ae.png)
Do you know what might be wrong?

**Comment by godunko** [comment]
This issue is not related to GNAT Studio: GDB is unable to find debug information for Ada runtime library to set breakpoint necessary to catch exceptions. You need to check compiler/GDB.

**Comment by m-kru** [comment]
Yes, I know, but what do you mean by check?

**Comment by m-kru** [comment]
For anyone having the same issue.

The problem is probably due to the fact, that you use GNAT shipped (installed) with your Linux distribution. Such GNAT builds usually do not provide debug info for runtime libraries. GNAT Community must be used. GPS first checks your `PATH`, if it does not find GNAT in `PATH`, it uses the one from `/bin` directory from GNAT Community.
