### ISSUE TITLE
Missing laltools directory

### ISSUE THREAD

**Issue by rogermc2** [AdaCore/gps#102]
`lal_core.gpr` withs `../laltools/src/lal_tools` but there is no `laltools` directory in the current `gps-master` distribution.
Also `with "../shared"` perhaps  should be `with "../share"`? 

[lal_core.gpr.zip](https://github.com/AdaCore/gps/files/4685696/lal_core.gpr.zip)

**Comment by steve-cs** [comment]
Creating and populating a ./laltools directory from the libadalangtools repository should resolve that dependency.

**Comment by rogermc2** [comment]
Many thanks for your easy solution.
