### ISSUE TITLE
"T305-028 Don't use relative paths to project files of subprojects" breaks my gps build?

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/gps#105]
My previously working gps build is now failing almost immediately with:

```
make -C gnatstudio default
make[2]: Entering directory '/home/travis/gnat-builder/gps-build/gnatstudio'
cd ../kernel/src; python hooks.py
cd ../kernel/generated; gnatcoll_db2ada \
          -api=GPS.Kernel.Properties.Database -adacreate -dbtype sqlite\
          -dbmodel=../src/properties_schema.txt
gprbuild  -m -p -ws \
  -XBUILD=Debug -XOS=unix -XLIBRARY_TYPE=relocatable -XXMLADA_BUILD=relocatable -Pgps -largs `pkg-config gmodule-2.0 --libs`
prj_editor.gpr:2:06: unknown project file: "lsp"
prj_editor.gpr:2:06: imported by "/home/travis/gnat-builder/gps-build/prj_editor/prj_editor.gpr"
prj_editor.gpr:2:06: imported by "/home/travis/gnat-builder/gps-build/ada_module/ui/ada_module_ui.gpr"
prj_editor.gpr:2:06: imported by "/home/travis/gnat-builder/gps-build/gnatstudio/gps.gpr"
lal_core.gpr:2:06: unknown project file: "lal_tools"
lal_core.gpr:2:06: imported by "/home/travis/gnat-builder/gps-build/lal/lal_core.gpr"
lal_core.gpr:2:06: imported by "/home/travis/gnat-builder/gps-build/lal/lal.gpr"
lal_core.gpr:2:06: imported by "/home/travis/gnat-builder/gps-build/gnatstudio/gps.gpr"
gps_lsp_client.gpr:1:06: unknown project file: "lsp_client_glib"
gps_lsp_client.gpr:1:06: imported by "/home/travis/gnat-builder/gps-build/lsp_client/gps_lsp_client.gpr"
gps_lsp_client.gpr:1:06: imported by "/home/travis/gnat-builder/gps-build/gnatstudio/gps.gpr"
gprbuild: "gps" processing failed
```
Full log: https://travis-ci.org/github/steve-cs/travis-test/builds/697314807

I think that the T305-028 commit https://github.com/AdaCore/gps/commit/aca065a4ba6edf3b8b04acc3a42952516506d0ad might be related.  This seems to indicate that the source for libadalang-tools and ada_language_server has moved within the gps build directory.

Currently I create the gps-build directory
```
mkdir -p gps-build  gps-build/laltools gps-build/ada_language_server
cp -a gps-src/* gps-build
cp -a libadalang-tools-src/* gps-build/laltools
cp -a ada_language_server-src/* gps-build/ada_language_server
```

Will moving the sources somewhere else in the tree allow the gps to build properly, or do I now need to build and install libadalang-tools and ada_language_server separately, or am I barking up the wrong tree?

Please advise.

**Comment by godunko** [comment]
Location of external repositories is flexible now. You need to configure GPR_PROJECT_PATH to point to directories of GPR files for all subprojects (they are <ada_language_server>/gnat, <libadalang-tools>/src, <VSS>/gnat).

**Comment by godunko** [comment]
Also, for convenience of developers and some build systems, there is 'subprojects' directory now, we use it to checkout source code of external projects. However, GPR_PROJECT_PATH need to be adjusted anyway.

**Comment by steve-cs** [comment]
Thanks for the clue.  I've moved ada_language_server and laltools source under 'subproject' and added the environment variable  GPR_PROJECT_PATH as you suggested and the top level gprbuild makes progress finding both lsp and laltools.  However now it appears to fail to find gnatcoll_text.gpr.  gnatcoll_text.gpr doesn't appear to be in my gnatcoll-core, gnatcoll-bindings or gnatcoll-db builds.  In fact the only place I can find a reference to "gnatcoll_text" is in ada_language_server.

This also appears to be related to a T305-028 commit (https://github.com/AdaCore/ada_language_server/commit/c5056ee011f109cca7253d324c35965813f328ab) which was also merged very recently.  Is this as simple as waiting for gnatcoll to catch up or should I open an issue against ada_language_server or gnatcoll or am I missing or misunderstanding something else?

```
export GPR_PROJECT_PATH=../subprojects/ada_language_server/gnat:../subprojects/laltools/src \
&& make -C gps-build PROCESSORS=0
make[1]: Entering directory '/home/steve/gnat-builder/gps-build'
make -C gnatstudio default
make[2]: Entering directory '/home/steve/gnat-builder/gps-build/gnatstudio'
cd ../kernel/src; python hooks.py
cd ../kernel/generated; gnatcoll_db2ada \
          -api=GPS.Kernel.Properties.Database -adacreate -dbtype sqlite\
          -dbmodel=../src/properties_schema.txt
gprbuild  -m -p -ws \
  -XBUILD=Debug -XOS=unix -XLIBRARY_TYPE=relocatable -XXMLADA_BUILD=relocatable -Pgps -largs `pkg-config gmodule-2.0 --libs`
lsp.gpr:19:06: unknown project file: "gnatcoll_text"
lsp.gpr:19:06: imported by "/home/steve/gnat-builder/gps-build/subprojects/ada_language_server/gnat/lsp.gpr"
lsp.gpr:19:06: imported by "/home/steve/gnat-builder/gps-build/prj_editor/prj_editor.gpr"
lsp.gpr:19:06: imported by "/home/steve/gnat-builder/gps-build/ada_module/ui/ada_module_ui.gpr"
lsp.gpr:19:06: imported by "/home/steve/gnat-builder/gps-build/gnatstudio/gps.gpr"
gprbuild: "gps" processing failed
Makefile:42: recipe for target 'all' failed
make[2]: *** [all] Error 4
make[2]: Leaving directory '/home/steve/gnat-builder/gps-build/gnatstudio'
Makefile:21: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/steve/gnat-builder/gps-build'
Makefile:701: recipe for target 'gps' failed
make: *** [gps] Error 2
```

**Comment by godunko** [comment]
It is new dependency, see https://github.com/AdaCore/VSS. Name of the project file will be changed to resolve this misconception at some point.

**Comment by steve-cs** [comment]
All good now.  Thanks!

**Comment by godunko** [comment]
You are welcome!
