### ISSUE TITLE
Monospace font is not monospace.

### ISSUE THREAD

**Issue by m-kru** [AdaCore/gps#106]
![image](https://user-images.githubusercontent.com/26227737/85515787-ce41e600-b5fd-11ea-9f0f-d065d5b1c2f3.png)

![image](https://user-images.githubusercontent.com/26227737/85515914-f0d3ff00-b5fd-11ea-8079-0d224fdcd9a9.png)

**Comment by setton** [comment]
Hello @m-kru - GNAT Studio relies on the OS to give it a monospace font (and usually, when the font "Monospace" is available, it is in fact an alias to a monospace font)... I suggest you change manually the font to choose a monospace one.
