### ISSUE TITLE
GNATDoc as an independant project.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#110]
Hello,
On AdaCore [Community](https://www.adacore.com/download), GNATStudio is no more provided on all targets, especially macOS :-(. Building it is not an easy way. Therefore GNATDoc, which is currently part of the same project, is also no more available. Could you put GNATDoc sources in a separate project which would be, I hope, easier to build?
Thanks, Pascal.

**Comment by godunko** [comment]
Pascal,

GNATdoc will be ported to new technology and will be available in libadalang-tools repository in the future.

**Comment by Fabien-Chouteau** [comment]
@Blady-Com you can still use GNATdoc from GNAT Community 2019
