### ISSUE TITLE
Build mess with many library dependancies.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#118]
Hello,
I try to build GNAT Studio for macOS 11.
My last attempt was not very successful (see announcement https://hermes.gwu.edu/cgi-bin/wa?A2=ind2006&L=GNAT-OSX&P=63) with several limitations.
One major difficulty is to synchronize GPS sources with all its library dependancies.
A welcome help would be a table with dependancy commit hash.
A simple text file which list Github commits for every live GPS source branches would be convenient. (I'm specifically interested in branch gtk-3.24)
For instance, dependancies.txt:
libadalang commit 398acf2c088ff385be40bc2d1a5ada866cd6eda7
gnatcoll-core commit 5830eac23f784aaa312ac071505a600bd4a6b328
langkit commit 024d02ff7b064b2f44f68c72c723c2af1e9ec7d9
vss commit xxxx
spawn commit yyyy
ada-language-serveur zzzz
etc.
The file is then updated each time required by using an other commit for a given dependancy.
Any other idea is welcome.
Thanks for your help, Pascal.

**Comment by godunko** [comment]
gtk-3.24 branch is still work in progress and not ready for real use.

One of solution to have synchronized sources for all dependencies is to use source code provided with GNAT Community Edition 2021, otherwise you need to play with commits around some date to find good candidate.

**Comment by Blady-Com** [comment]
Thanks Vadim for your kind answer, I'll go further in the way you advise me.
But I can't find the source codes to build GNAT Studio in CE 2021 of any platform (Windows or Linux).
What is way to get them?

**Comment by godunko** [comment]
Thank you for your report, this is an issue on our side, source code of all components will be available soon.

**Comment by Blady-Com** [comment]
One other suggestion could be to add a label (CE-2021 for instance) on each concerned Github repo, couldn't it be?

**Comment by Fabien-Chouteau** [comment]
> One other suggestion could be to add a label (CE-2021 for instance) on each concerned Github repo, couldn't it be?

Sorry @Blady-Com this is not part of our procedures for GNAT Community release and we won't change for now.

**Comment by Xiretza** [comment]
[Many](https://github.com/AdaCore/gnatcoll-core/releases/tag/v21.0.0) [AdaCore](https://github.com/AdaCore/gprbuild/releases/tag/v21.0.0) [projects](https://github.com/AdaCore/gtkada/releases/tag/v21.0.0) [have](https://github.com/AdaCore/xmlada/releases/tag/v21.0.0) [release](https://github.com/AdaCore/gnatcoll-bindings/releases/tag/v21.0.0) [tags](https://github.com/AdaCore/libadalang/releases/tag/v21.0.0), can't this same workflow be used for GNAT Studio as well?

**Comment by Fabien-Chouteau** [comment]
> [Many](https://github.com/AdaCore/gnatcoll-core/releases/tag/v21.0.0) [AdaCore](https://github.com/AdaCore/gprbuild/releases/tag/v21.0.0) [projects](https://github.com/AdaCore/gtkada/releases/tag/v21.0.0) [have](https://github.com/AdaCore/xmlada/releases/tag/v21.0.0) [release](https://github.com/AdaCore/gnatcoll-bindings/releases/tag/v21.0.0) [tags](https://github.com/AdaCore/libadalang/releases/tag/v21.0.0), can't this same workflow be used for GNAT Studio as well?

These are not GNAT Community releases, as I mentioned the process is not the same for GNAT Community release and we won't change for now.

**Comment by Blady-Com** [comment]
> Thank you for your report, this is an issue on our side, source code of all components will be available soon.

GPS components have been now released on Community web page. Thanks!
In order to help in the GPS building process, could you please give the version used of Python, PyCairo and PyGObject in CE 2021?
