### ISSUE TITLE
Gnatpp spawning issue with -X switch.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#20]
Hello,
On the command line the following gnatpp invocation is fine:
cmd$ gnatpp -P test16.gpr -XLIB_COMPONENTS_BUILD2=default -XLIB_COMPONENTS_BUILD1=default test16.adb

But in GPS the invocation of pretty printer with project test16.gps on test16.adb gives the error:
gnat pretty -rf -Ptest16.gpr -XLIB_COMPONENTS_BUILD2=default -XLIB_COMPONENTS_BUILD1=default test16.adb
gnatpp: test16.gpr:7:04: warning: value "default -XLIB_COMPONENTS_BUILD1=default " is illegal for typed string "build2"
try "gnatpp --help" for more information.

I guess it's a GPS issue rather than gnatpp.

See project and source code in attached files.

HTH, Pascal.

[Test16.zip](https://github.com/AdaCore/gps/files/1236474/Test16.zip)

**Comment by setton** [comment]
Hi @Blady-Com,  this should have been fixed in the current sources with 032ca0d, let us know if not.

**Comment by Blady-Com** [comment]
Hello Nicolas,
Thanks for the fix.
I'm not yet in position to build last GPS sources but in a quick read I saw this small typo in common/core/src/command_lines.adb:
--  One parameter is already foung,
Regards, Pascal.

**Comment by Blady-Com** [comment]
Hello Nicolas,
I tried to build GPS from source (today master branch), but I guess the GPS repository lacks for laltools directory needed in lal/lal.gpr:
with "../laltools/src/lal_tools";
Where could I find laltools?
Thanks, Pascal.

**Comment by setton** [comment]
hmhm looks like this is not yet a public repository. I’ll ask around, hopefully we can get out of this knot soon.

**Comment by caloo** [comment]
I'm also trying to build gps from the master branch and the repository seems still lacking the laltools:
`lal_core.gpr:3:06: unknown project file: "../laltools/src/lal_tools"
`
