### ISSUE TITLE
gps RPATH broken

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/gps#25]
It appears that RPATH was deliberately disabled in DEBUG builds in a temporary workaround 11 months ago by the following commit: https://github.com/AdaCore/gps/commit/12956e63250aac8c5af39378f9bb68fad8a5e735

Is there any reason that this should not be reverted at the present time?

My observation is if it were reverted, RPATH is still not quite right as it contains extra ".." compared to some of the other Adacore builds, e.g. gnatcoll_db2ada, but a simple ln -s seems to cure that and make gps runnable.  Specifically if building with "prefix=$PWD/gnat", a workaround seems as simple as "ln -s $PWD/gnat ../gnat".

Working relative RPATH seems useful to me.  Both for convenience in development and portable builds without shell wrappers.  The above commit blocks that.  A proper patch to the build is not immediately obvious to me without some reorganizing of the overall gps source tree.

What am I missing?

**Comment by AnthonyLeonardoGracio** [comment]
Hello Steve, 

The patch has been reverted and GPS builds and run fine: thanks for suggesting this!

Regards,
