### ISSUE TITLE
[20180611] invalid switch: -gnat95    [Ada]          prep.adb

### ISSUE THREAD

**Issue by aplatypus** [AdaCore/gps#27]
I have a pre-existing GPS project (.GPR) file for an old project that has worked fine previously.  Unfortunately this is replacement PC and after I installed the recent community GPS the project won't build any more using `gnatmake`.

I am getting the following error on every file:

            :
        gnat1: invalid switch: -gnat95
            [Ada]          comms.adb        
            :
        gnat1: invalid switch: -gnat95
            [Ada]          common_types.ads
           :

I downloaded the file today (2018-06-29):

-  gnat-community-2018-20180611
    - `gnat-community-2018-20180611-x86_64-windows-bin.exe` installer

I've been checking through the `gnatmake` and `gnat` help messages.  I've only seen and  option for 2012 which is the default anyway.  No Ada 95-s of Ada 2005-s

     -gnat2012 Ada 2012 mode (default)

The project file has not been changed since 2015 according to the SVN log.  When I checked the build settings on GPS sets "`-ada95`" for ADA '95 compatibility.  It is not normally something one does manually.  And yet, there seems to be no option on gnat or gnatmake to choose/specify Ada '95.

Is this a GPS error or is this something gone amiss with the GNAT tooling?  Project file is pasted in below (the key bits).

One further **non-useful** '_feature_' is that reporting a version is not turnned on for `gnat1` 

       \gnat1.exe --help
           :
       -version                              [disabled]

----[ project file ]----

Trimmed down:
```
   for Source_Dirs use ("src/**");
   for Object_Dir use "../build/obj";
   for Source_Files use ( ... "common_types.ads", "comms.adb", "comms.ads", ... );

   package Compiler is
      for Switches ("ada") use ("-O2", "-gnatQ", "-gnat95");
   end Compiler;

   package Builder is
      for Default_Switches ("ada") use ("-k", "-j2", "-s");
   end Builder;

   package Naming is
      for Casing use "lowercase";
   end Naming;
```

-----[ versions ]----

**gnatmake**
```
gnatmake.exe --version
GNATMAKE Community 2018 (20180523-73)
Copyright (C) 1995-2018, Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**gnat**
```
gnat --version
GNAT Community 2018 (20180523-73)
Copyright (C) 1996-2018, Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**gnat1**
```
-version                              [disabled]
```

**Comment by aplatypus** [comment]
I made some follow-up.  The MSYS2 on Windows 64 `pacman` Ada compiler is GCC v7.3.

```
mingw-w64-x86_64-gcc-ada 7.3.0-2 (mingw-w64-x86_64-toolchain)
    GNU Compiler Collection (Ada) for MinGW-w64

gnatmake.exe  --version
GNATMAKE 7.3.0
Copyright (C) 1995-2017, Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This Ada compiler supports the -ada95 switch and all the Ada-s:
```
Usage: gnat1 switches sfile

  sfile     Source file name

  -g            Generate debugging information
  -Idir         Specify source files search path
  -I-           Do not look for sources in current directory
  -O[0123]      Control the optimization level
   
    :

  -gnatyN   Cancel all previously set style checks
  -gnatzc   Distribution stub generation for caller stubs
  -gnatzr   Distribution stub generation for receiver stubs
  -gnat83   Ada 83 mode
  -gnat95   Ada 95 mode
  -gnat2005 Ada 2005 mode
  -gnat2012 Ada 2012 mode (default)
  -gnat-p   Cancel effect of previous -gnatp switch

        .file   "<stdin>

```
And I was able to run the compiler OK without the `invalid switch` error.

So there is a workaround for anyone passing this way and not having access to Ada 83, 95 and 05.

_**Alas**_ ... the GNU `gnat1` version is actually even LESS helpful.  There is no version option at all (not even a disabled one). 👎

**Comment by reznikmm** [comment]
GNAT community Edition doesn't support Ada before Ada 2012. See [here](https://www.adacore.com/gnatpro/comparison).
Use other compiler or remove `-gnat95` from your project file.

This is definitely not a GPS bug.
