### ISSUE TITLE
GPS issue with Python console.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#32]
Hello,
After opening a Python Console, when you quit Python with "quit()" then GPS also exits.
GPS logs are:

> [GPS.KERNEL.ACTIONS] Entering GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 Execute action open python 1 times synchronous=FALSE (10:07:17.397)
>    [GPS.KERNEL.GPS_KERNEL] Refresh_Context Python (10:07:17.419)
> [GPS.KERNEL.ACTIONS] Leaving GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 (10:07:17.420)
> [GPS.KERNEL.ACTIONS] Entering GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 Execute action Copy to Clipboard 1 times synchronous=FALSE (10:09:05.687)
> [GPS.KERNEL.ACTIONS] Leaving GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 (10:09:05.778)
> [GPS.KERNEL.ACTIONS] Could not execute "Python Auto Indentation" (10:09:38.552)
> [PYTHON.ERROR] Exception SystemExit(None,) (10:09:38.575)

How to prevent GPS exit?
Thanks, Pascal.

**Comment by reznikmm** [comment]
Python interpreter is important part of GPS and GPS is unable to run without it. So you mustn't quit Python in Python Console. You can just close Python Console, however.

Best regards

**Comment by Blady-Com** [comment]
Thanks Maxim for your explanation.
I thought that gps launch python as a new sub-process.
Regards, Pascal.
