### ISSUE TITLE
GPS issue with outline internal package.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#33]
Hello,
Public object K and private object J of internal package P1 in test03.adb are not displayed in outline view, see attached test03.adb and test03.png.
Whereas public object K and private object J of package P1 in test04.ads are displayed in outline view, see attached test04.ads and test04.png.
Shouldn't objects of P1 in test03.adb be also displayed?
HTH, Pascal.
[test03.adb.txt](https://github.com/AdaCore/gps/files/2320575/test03.adb.txt)
[test04.ads.txt](https://github.com/AdaCore/gps/files/2320576/test04.ads.txt)
![test03](https://user-images.githubusercontent.com/24991522/44617643-a731f600-a866-11e8-8331-4cc87fdbad54.png)
![test04](https://user-images.githubusercontent.com/24991522/44617644-a731f600-a866-11e8-91dc-ef064db9a324.png)

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

We are not able to reproduce that issue on the current development version, so this has been probably fixed from then.

Nevertheless, thanks for reporting that issue!

Regards,

**Comment by Blady-Com** [comment]
Hello, FYI the issue is still present in GPS Community 2019, regards Pascal.

**Comment by Blady-Com** [comment]
Hello, the issue is still present in GNAT Studio 2026.2, regards Pascal.
