### ISSUE TITLE
GPS doesn't compile example GTKada program...

### ISSUE THREAD

**Issue by edgspc** [AdaCore/gps#34]
Hi
I have installed Ada and Gtkada as per instructions on Ubuntu 18.04 x64.
I have 3.22.30-1ubuntu1 gtk dev from apt-get...
GTKada compiles fine, and the test application runs ok.
I seem to have set the project paths ok - "with gtkada" seems to work.

Load up the default GTKada example in GPS.
Hit compile and GPS errors with:

/usr/lib/x86_64-linux-gnu/libpng16.so.16: undefined reference to `inflateValidate@ZLIB_1.2.9'
/usr/lib/x86_64-linux-gnu/libgtk-3.so: undefined reference to `pango_fc_font_map_config_changed'

**Running gprbuild in the terminal with the same .gpr file compiles and runs ok.**

Is this the same issue as #31? Where the GPS startup script is changing environment variables....
Is there any solution aside from compiling GPS with the same version of GTK as installed systemwide?

Running with -v in both GPS and terminal produces the same output (aside from the error with GPS).

Is there anything else to try or set that might resolve this?

thanks
gb

**Comment by godunko** [comment]
It setup issue. You can remove system's development package for Gtk and setup environment to use everything from GtkAda package.

**Comment by haidarsoft** [comment]
I have same problem.
Could you please elaborate more on how to remove the system GTK package and use GtkAda?

**Comment by godunko** [comment]
Package management is OS specific feature and it is mostly impossible to provide detailed information. You need to check documentation for your OS/version.

Also, you can use 'ldd <some_gtkada_application>' to get list of shared libraries, find all Glib/Gtk+/Pango/CAIRO related libraries, and remove corresponding system's <lib>-devel packages.

**Comment by fxcqz** [comment]
For what it's worth, logging off then logging in and restarting GPS fixed this for me.

**Comment by SMerrony** [comment]
Same problem here.  Removing -dev packages made things worse. 

I have got the example program to build by adding `-lz -lpangoft2-1.0` to the Build>Switches>Ada Linker properties of the project.

**Comment by heharkon** [comment]
@haidarsoft 
I had this same issue with Ubuntu 19.04. 

I purged **libpango1.0-dev** with apt and it removed a bunch of other dev packages as well:

```
Removing libgtk-3-dev:amd64 (3.24.8-1ubuntu1) ...
Removing libpango1.0-dev:amd64 (1.42.4-6) ...
Removing libharfbuzz-dev:amd64 (2.3.1-1) ...
Removing gir1.2-harfbuzz-0.0:amd64 (2.3.1-1) ...
Removing libicu-dev:amd64 (63.1-6) ...
Removing icu-devtools (63.1-6) ...
Removing libatk-bridge2.0-dev:amd64 (2.32.0-1) ...
Removing libatk1.0-dev:amd64 (2.32.0-1) ...
Removing libatspi2.0-dev:amd64 (2.32.0-1) ...
Removing libcairo2-dev:amd64 (1.16.0-4) ...
Removing libcairo-script-interpreter2:amd64 (1.16.0-4) ...
Removing libepoxy-dev:amd64 (1.5.3-0.1) ...
Removing libfribidi-dev:amd64 (1.0.5-3.1) ...
Removing libgraphite2-dev:amd64 (1.3.13-7) ...
Removing libharfbuzz-gobject0:amd64 (2.3.1-1) ...
Removing libpixman-1-dev:amd64 (0.36.0-1) ...
Removing libxcb-shm0-dev:amd64 (1.13.1-2) ...
Removing libxcomposite-dev:amd64 (1:0.4.4-2) ...
Removing libxtst-dev:amd64 (2:1.2.3-1) ...
Removing pango1.0-tools (1.42.4-6) ...
Removing wayland-protocols (1.17-1) ...
Removing x11proto-composite-dev (1:2018.4-4) ...
Removing x11proto-record-dev (2018.4-4) ...

```

And after that restarted GPS and it worked ok.

**Comment by heharkon** [comment]
Actually, quite tricky situation, since I wanted to use glade to design my gtk view, and installing that with the package manager installs all those packages back...
