### ISSUE TITLE
How to translate GPS to my native language?

### ISSUE THREAD

**Issue by vrozsas** [AdaCore/gps#38]
Hello!
I want to translate GPS' user interface to Brazilian Portuguese.
I feel that Ada would be more widely adopted if it were more "universal" and accessible to more peoples.
GPS is the main IDE for Ada, so translating it to other languages is very important to spread Ada throughout the world.

How does the translation process work?
Where do I begin?
Does GPS have a project in any kind of service like Transifex?
Thanks in advance for the answers.

**Comment by vrozsas** [comment]
By the way, I want to do it voluntarily, for free. 😊

**Comment by reznikmm** [comment]
Hello!
This would be wonderful, but this may require some coding, because i18n support in GPS is in its infancy.
You can start with translating share/menus.xml.

**Comment by vrozsas** [comment]
Oh, I thought you guys had a central string file, like in the case of Android apps (res/values/strings.xml).
This would make translators' lives a lot easier. 😁
