### ISSUE TITLE
Vim plugin - cW incorrect

### ISSUE THREAD

**Issue by TamaHobbit** [AdaCore/gps#46]
Pressing cW should change until the end of a word delimited by whitespace, seeing other symbols all as part of the word. Instead, the current character is first removed and then a capital W is inserted. The first bug is that a character instead of a word is replaced. The second bug is that this is done with two actions, so that pressing u to undo, only half undoes the action.

**Comment by AnthonyLeonardoGracio** [comment]
See answer on #36
