### ISSUE TITLE
Vim plugin - w motion bounded by numbers

### ISSUE THREAD

**Issue by TamaHobbit** [AdaCore/gps#52]
If you have the cursor in a word before a number, cw should consider the number part of the word, but the plugin implementation considers that a word boundary. For instance, dw with the cursor at the beginning of thisIdentifierHas2NumbersIn8It should delete the whole word. In the plugin as it is currently implemented, this takes five dw commands.

**Comment by AnthonyLeonardoGracio** [comment]
See answer on https://github.com/AdaCore/gps/issues/36
