### ISSUE TITLE
Missing line numbers

### ISSUE THREAD

**Issue by iandoug** [AdaCore/gps#53]
Hi

See screenshot, my version is missing line numbers. I have selected "all line numbers" in the Options.
Version: 2018, Gentoo Linux.
I was told on Ada group (comp.lang.ada?) that this was a problem in 2016 version which was supposed to be fixed, so maybe it's just my system that has some other problem?

![image](https://user-images.githubusercontent.com/12673886/50363398-19e08300-0574-11e9-9ee3-a55f37e34511.png)

Thanks, Ian

**Comment by ogorodnik** [comment]
Hello,
We can not reproduce this issue with development version of GPS. It seems that issue has already been fixed.
Thank you for the report.

**Comment by atupone** [comment]
The problem seems to happen when moving to gtk+-3.20 or later

**Comment by iandoug** [comment]
@atupone 
Mmm okay....
x11-libs/gtk+  : I have both 2.24.32-r1 and  3.24.1 installed. Should I maybe set a use flag or somesuch to force it to use the older version?

**Comment by atupone** [comment]
I guest 2.24 is not compatible. 3.24 is too early. I installed here the 3.18 from an old ebuild and it works. So nothing in the gentoo tree is good at the moment. I will search for a fix

**Comment by ogorodnik** [comment]
We are already working on updating Gtk for GPS so I guess it is not strongly needed to spend time for searching such fix.

**Comment by iandoug** [comment]
Okay I'll wait. Assume the tweaks to Gtk will also address the other issue of selected text (for copy operations etc) not being highlighted correctly ... coloured text just changes to default grey and no background colour applied. Was only going to raise this issue after current issue sorted, assumed fixing one might fix the other.

**Comment by atupone** [comment]
I don't see any gps-2019 source on adacore

> We are already working on updating Gtk for GPS so I guess it is not strongly needed to spend time for searching such fix.

I don't see any gps 2019 source on adacore :(
Everything seems released except gps and gnatcoll.db sources

**Comment by ogorodnik** [comment]
@atupone 
gnat-community-2019-20190517-x86_64-linux-bin contains GPS, you should simple download one this package and install it. You will have compiler, tools and GSP.

**Comment by atupone** [comment]
But not the source. I need the source to package in gentoo. Why are they missing this year?

**Comment by Entomy** [comment]
I know this is extremely late, but I looked into this because I know how important it is to have the sources on source based systems. It seems this was partially caused by how AdaCore restructured the downloads page. Regardless of whether it detects your platform correctly, click the link below the downloads that says "More platforms, packages, versions and sources", and then make sure it's still on your platform. Then for the product you want, at the bottom of that section is a link for "Sources". From there you'll be looking for "gnat-2019-*.src.tar.gz", which should have everything you need.

**Comment by 1ma** [comment]
I'm experiencing these issues in Ubuntu 18.04 and 20.04, on stock installations from standard packages:

Ubuntu 18.04:
gnat-gps package: 6.1.2016
libgtk-3-0 package: 3.22.30

Ubuntu 20.04:
gnat-gps package: 19.2
libgtk-3-0 package: 3.24.18
