### ISSUE TITLE
Find / Replace with an empty string breaks future Find functionality

### ISSUE THREAD

**Issue by rtyler** [AdaCore/gps#54]
**Steps to reproduce**

. Open a source file in the Editor view
. Open the "Search" view
. Enter a valid "Find" query into the "Find" field (e.g. `package)
. Leave "Replace" empty, such as you might when you're trying to replace something with an empty string
. Select "Where" of **Whole Text** in **Current File**.

**Expected**

The occurrences of "package" to be replaced by an empty string

**What happened**

* The "Messages" view logged `Finished replacing the string in current file (0 occurrences)`
* The "Replace" operation failed.
* Subsequent "Find" operations fail to work until GPS is restarted.

**Environment**

```
GPS 2018 (20180528) hosted on x86_64-pc-linux-gnu
GNAT Community 2018 (20180524-73)
```

**Comment by ogorodnik** [comment]
Hello,
We can not reproduce this issue with development version of GPS. It seems that it has already been fixed.
Thank you for the report.
