### ISSUE TITLE
Feature suggestion: Use tab characters (\t) for indentation.

### ISSUE THREAD

**Issue by david-tamar** [AdaCore/gps#56]
Most IDEs allow to switch between spaces and tabs for indentation, and the size of tabs as well.

I usually use 4-space long tabs for indentation everywhere else, and I think it has a significant impact on my programming experience.

I turned on "use tabulations" in Ada's settings, and the indentation length to 4, however when I press tab or reformat the code, I still get plain spaces.

**Comment by ogorodnik** [comment]
We can reproduce this issue and investigate it. However, in general, I would not recommend to use "tab" in source codes. Auto indentation works pretty well in GPS and in most of cases you should not have to align lines at all. On the other hand using "tab" can bring decreasing readability because in different editors it can have different length.

**Comment by Entomy** [comment]
I've been complaining about this for about 5 years now to no avail, so... good luck.

 You _can_ absolutely get tabs to work, but bizarrely GPS only respects this if you also set the Indentation numbers to 8, not the 4 you would expect. This happens to also mean tab stops are abnormally large. Also, GPS's snippets don't care at all about what your preferences are and will insert things using its defaults, so get used to `gnatpp`ing everything.

@ogorodnik Or it can increase readability by allowing the reader to set whatever equivalent value they find most easy to read. I have cognitive difficulties and happen to strongly prefer what source code is tab indented. AdaCore's default policy of 3 spaces is so small for me that trying to read your source code for more than a few minutes gives me a migrane. The beauty of tab as indentation is that I can tell the editor to render it at what I prefer, and you can tell the editor to render it at what you prefer. Spaces don't do that.

**Comment by david-tamar** [comment]
> I've been complaining about this for about 5 years now to no avail, so... good luck.
> 
> You _can_ absolutely get tabs to work, but bizarrely GPS only respects this if you also set the Indentation numbers to 8, not the 4 you would expect. This happens to also mean tab stops are abnormally large. Also, GPS's snippets don't care at all about what your preferences are and will insert things using its defaults, so get used to `gnatpp`ing everything.
> 
> @ogorodnik Or it can increase readability by allowing the reader to set whatever equivalent value they find most easy to read. I have cognitive difficulties and happen to strongly prefer what source code is tab indented. AdaCore's default policy of 3 spaces is so small for me that trying to read your source code for more than a few minutes gives me a migrane. The beauty of tab as indentation is that I can tell the editor to render it at what I prefer, and you can tell the editor to render it at what you prefer. Spaces don't do that.

Well, I now returned to try GPS again after a few months, and the bug still persists.
No tabs, just spaces. I took your suggestion and indeed it does tabs only with 8 spaces which is strange, but it's far better than using spaces (in my humble opinion), therefore I'd stick with 8-spaces wide tabs rather than use plain spaces. I don't know why it is being ignored.

**Comment by Entomy** [comment]
@david-tamar I'm sorry man. People deserve better than this, but they won't listen to me.

**Comment by ogorodnik** [comment]
> Well, I now returned to try GPS again after a few months, and the bug still persists.
> No tabs, just spaces. I took your suggestion and indeed it does tabs only with 8 spaces which is strange, but it's far better than using spaces (in my humble opinion), therefore I'd stick with 8-spaces wide tabs rather than use plain spaces. I don't know why it is being ignored.

Due to the fact that this ticket is still open, I can say that it is not ignored. But you also should understand that we can't work on "community" tickets in high priority.

**Comment by ogorodnik** [comment]
BTW you can use code formatting just selecting code and pressing "tab" key. Hope this will help.

**Comment by Entomy** [comment]
@ogorodnik I first reported this in 2009 as a paying customer. My dude, it's not an issue of community tickets, it's an issue of AdaCore not caring. Shit like this is a major reason why I stopped paying.

**Comment by setton** [comment]
@Entomy - AdaCore treats this very seriously. Please DM me the AdaCore ticket if you have it, or the name under which you opened the ticket - I did not find your name in the database - and I will follow this up internally.

This is also not the place to make disparaging comments about any company - keep arguments at the technical level.
