### ISSUE TITLE
lal-highlighters.adb fails to compile (Langkit_Support.Token_Data_Handlers problem?)

### ISSUE THREAD

**Issue by steve-cs** [AdaCore/gps#57]
On my machine it appears that recent changes in libadalang and/or langkit have caused gps to no longer build successfully failing starting with the following error messages:

lal-highlighters.adb:26:21: warning: unit "Langkit_Support.Token_Data_Handlers" is never instantiated
lal-highlighters.adb:567:26: a generic package is not allowed in a use clause
lal-highlighters.adb:573:30: invalid prefix in selected component "Langkit_Support.Token_Data_Handlers"
lal-highlighters.adb:580:30: invalid prefix in selected component "Langkit_Support.Token_Data_Handlers"
lal-highlighters.adb:595:16: "First_Token_Or_Trivia" is not visible
[...]

I'm guessing (hoping) that gps is out of sync with libadalang in the public repositories.  If so, I can easily wait; it's not blocking anything I'm doing.  However if it's my problem I'd like to fix my own daily builds.

**Comment by setton** [comment]
Hello,

GPS needs to be built against the "stable" branch of libadalang/langkit.

Let us know if this doesn't help!

**Comment by steve-cs** [comment]
I should have checked that first.  GPS master against libadalang-tools master, libadalang stable, langkit stable does build.

Thanks!
