### ISSUE TITLE
Project'Target is empty with GPS.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#58]
Configuration: GNAT Community 2018 on macOS.

Given the following project file:

```
project Test27 is
  OS := Project'Target;
  for Object_Dir  use "objos" & "/" & OS;
  package Compiler is
     case OS is
       when "*linux*" | "unix" =>
         for Switches ("Ada") use ("-gnath");
       when "*windows*" =>
         for Switches ("Ada") use ("-gnatP");
       when "*darwin*" =>
         for Switches ("Ada") use ("-gnatA");
       when others =>
         null;
     end case;
   end Compiler;
end Test27;
```
See [test27.gpr.txt](https://github.com/AdaCore/gps/files/2949248/test27.gpr.txt)

When I open it with GPS, the Project'Target seems to be empty as logged by GPS the object directory is not set with the target name:
[2019-03-09 22:36:43] /Tests/test27.gpr:3:25: warning: object directory "objos/" not found

But with it seems to be correct with GPRBUILD as the object directory is set with target name:
$ gprbuild -P /Tests/test27.gpr 
test27.gpr:3:25: object directory "objos/x86_64-darwin" not found
gprbuild: "/Tests/test27.gpr" processing failed

HTH, Pascal.

**Comment by ogorodnik** [comment]
Hello,
This issue has been already fixed in development version of GPS. Next major release of GPS will contain the fix.

**Comment by Blady-Com** [comment]
Maybe a regression occurred.

GPR file test27.gpr:
```
project Test27 is
   OS := Project'Target;
   for Warning_Message use "OS " & OS & " is used";
end Test27;
```
With GNAT Studio 2026.2, Project'Target is empty:
`[2026-08-11 21:34:06] /Users/me/test27.gpr:1:09: warning: OS  is used`

With GPRBuild, Project'Target is correct:
```
gprbuild -P test27.gpr
test27.gpr:1:09: warning: OS x86_64-darwin is used
```
