### ISSUE TITLE
Side panels disappear after new project is opened

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gps#59]
The side panels (Project, Outline, and Scenario by default) will disappear each time a project is opened that has not been opened before.

Reproduce with:
Open Default project
File->Close All
Open any project, side panels immediately disappear
View->Project
View->Outline
View->Scenario
Open any project, side panels immediately disappear

Occured with 20180523-73 on Windows 10 (x64)

**Comment by ogorodnik** [comment]
We can't reproduce this with development version of GPS. I would also recommend to remove "user_home"\.gps directory, probably this will help. GPS will create new "clean" one on startup.
