### ISSUE TITLE
Can't open project with missing dependency

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gps#60]
Opening a GPR project (let's call it B), which has a dependency to another GPR project (let's call it A), fails with `unknown project file: "A"`

While obviously building a project without it's dependencies should fail, it doesn't seem right that I can't even view the sources of the project within GPS, nor edit the project file (through Project Properties; of course I can still open the GPR as a file). A simple typo in a dependency name could cause this to happen. This also means that entire chains of dependencies need to be installed just to _view_ sources, which if inspecting code from the internet before installing it... that's just remarkably inconvenient.

**Comment by ogorodnik** [comment]
In the location view you should have something like:
Project (1 item in 1 file)
  hello.gpr (1 item)
    1:6 unknown project file: "A"

If you double-click on the last line GPS will open this project file "as a file" and you can correct/modify it. After corrections you can reload this project via corresponding menu.
But GPS can't work with a project when a project file is incorrect. And right now we don't have plans to modify this. GPS not only opens and shows source files but also does a lot of work such as computing cross references, provide navigation trough code and so on and all this features can't be provided without a valid project file.

**Comment by Entomy** [comment]
So does Visual Studio. They just don't provide the features they can't make work with missing dependencies, but still do what they can with what they've got. In fact, so does literally every other IDE I've used. But okay.
