### ISSUE TITLE
Changes to scenario variables don't auto save project

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gps#62]
Changes to the scenario variables such as adding a new variable or adding a value for an existing variable do not auto save the project file, and require a manual save. This is in direct contrast to the Project Properties UI which does. As manually saving projects is a rather abnormal operation and is tucked away in a not-so-obvious location in the UI, this seems like a bug. At the very least, a UX inconsistency.

**Comment by ogorodnik** [comment]
Hello Entomy,
This issue has already been fixed in development version of GPS. The fix will be accessible in the next major release of GPS.
