### ISSUE TITLE
Adjusting project properties after creating scenario variable puts all adjustments within the scenario variable

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gps#63]
This is a remarkable convolution that's easier to show than tell, so I'll just leave it as the steps to reproduce and you can see for yourself.

Steps to reproduce:
Create a project with no scenario variables
Adjust some project properties (debug information, use mapping file, enable assertions, whatever)
Create scenario variable with at least two values
Adjust some project properties
Change value of the scenario variable
Adjust some project properties

Now view the GPR source

Pretty sure default behavior should be to apply the properties "globally" and require specific intervention to apply them only to a scenario variable. Or at least have something that easily enables setting these properties globally. Once a scenario variable has been created, there's no way through GPS to set the properties like they were before, other than to manually edit the GPR source.

**Comment by ogorodnik** [comment]
Hello Entomy,
We fill this as an enhancement request.
Thank you for the report.

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

This is now fixed in the GPS development version and the fix will also be available in the next community release.
