### ISSUE TITLE
Outline content stays displayed.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#64]
Hello,
When the last file editor is closed, the outline content stays displayed with the last content.

When test04.ads is opened:
![image](https://user-images.githubusercontent.com/24991522/55290367-aa7bfa00-53d2-11e9-846d-8dc291e2cb40.png)

When test04.ads is closed:
![image](https://user-images.githubusercontent.com/24991522/55290360-90421c00-53d2-11e9-8769-f62bb56ee4d9.png)

Configuration: GPS Community 2018, macos 10.13.6 (17G5019).

HTH, Pascal.

**Comment by ogorodnik** [comment]
Yes, it is a bug. Will be fixed.

**Comment by ogorodnik** [comment]
This issue has been fixed in development version of GPS. The fix will be accessible in the next major version of GPS.
