### ISSUE TITLE
Subprogram indication issue.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#66]
Hello,

When the cursor is on "set" procedure, the subprogram indication on the bottom left is "P1.get.set" instead of "P1.set":
![image](https://user-images.githubusercontent.com/24991522/55290889-237e5000-53d9-11e9-9e1a-a4622f933c33.png)

Source file:
[test04.ads.txt](https://github.com/AdaCore/gps/files/3026763/test04.ads.txt)

Configuration: GPS Community 2018, macos 10.13.6 (17G5019).

HTH, Pascal.

**Comment by ogorodnik** [comment]
This issue is already fixed in development version of GPS.
