### ISSUE TITLE
Unmatched strings break attribute highlighting transiently

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gps#69]
![image](https://user-images.githubusercontent.com/25399505/57341118-10148200-7107-11e9-8e42-eb022e311c26.png)

![image](https://user-images.githubusercontent.com/25399505/57341126-173b9000-7107-11e9-89f1-532be714f2ee.png)

Moving a quote between two lines, otherwise in the same part of an expression, with drastically different results as far as syntax highlighting goes.

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

The current highlighter is quite unstable indeed. We plan to switch to a complete new highlighting engine in the coming years. The new one will be based on libadalang, which will hopefully allow us to fix easily this kind of issues.

Regardsm

**Comment by Entomy** [comment]
So as I understand it, this was closed not because it was fixed, but because it can't be currently?

**Comment by AnthonyLeonardoGracio** [comment]
It has been closed because it lookss fixed with the highlighter based on libadalang yes. The problem with this highlighter (which can be enabled via a preference in the GPS dev version) is its performance, that's why we don't enable it by default.

Regards,
