### ISSUE TITLE
Running debug target before build target deletes breakpoints in editor

### ISSUE THREAD

**Issue by benconvey** [AdaCore/gps#70]
Admittedly, this wont happen often as I'd normally run clean, build and debug targets in that order, which works fine. However, whenever I've accidentally run clean and then debug targets  I've noticed all my breakpoints disappear.

It feels as though break points should persist in editor windows, regardless of target run, especially when the file is unchanged.
![Screen Shot 2019-05-08 at 21 57 20](https://user-images.githubusercontent.com/10352780/57408748-69031980-71de-11e9-989e-f44281147948.png)
![Screen Shot 2019-05-08 at 21 56 30](https://user-images.githubusercontent.com/10352780/57408750-69031980-71de-11e9-961c-74688562f2ff.png)

**Comment by benconvey** [comment]
[dissappearing breakpoints.zip](https://github.com/AdaCore/gps/files/3163213/dissappearing.breakpoints.zip)
Please see the zipped screen recording if unsure

**Comment by ogorodnik** [comment]
We can't  reproduce this issue with current developer version of GPS. It seems that the issue has been already fixed.
