### ISSUE TITLE
Bad en_US localization

### ISSUE THREAD

**Issue by Entomy** [AdaCore/gps#75]
![image](https://user-images.githubusercontent.com/25399505/58480068-89602d00-8127-11e9-9a9c-30f34ee140f2.png)

"also" and "create" should switch places

Also, considering they are called "body" in the ARM and even in the Ada source code (hell there's a "body" keyword), it would be clearer to newcomers what this is doing if it said "body" here as well, as a different word usually implies a different concept.

**Comment by ogorodnik** [comment]
This issue has been corrected in development version of GPS.
Thank you for the report.
