### ISSUE TITLE
No arm-eabi-gnatmake file

### ISSUE THREAD

**Issue by avraliov** [AdaCore/gps#76]
No arm-eabi-gnatmake file in ARM ELF (hosted on linux64) package

**Comment by ogorodnik** [comment]
We don't provide gnatmake anymore. You should use gprbuild instead.

**Comment by avraliov** [comment]
No gprbuild in options! screenshot uploaded

вт, 9 июл. 2019 г. в 18:18, Andry Ogorodnik <notifications@github.com>:

**Comment by ogorodnik** [comment]
This issue is not related to GPS. I guess it is better to ask directly in the gprbuild section
