### ISSUE TITLE
Running latest release on OSX El Capitan (10.11.6) fails error dyld: lazy symbol binding failed: Symbol not found: _getentropy

### ISSUE THREAD

**Issue by benconvey** [AdaCore/gps#78]
As per the title, running the latest version of GPS downloaded from the Adacore website on El Capitan fails with the above error. A bit of googling reveals its to do with Apple SDKs used at build time. Is this an issue with the install package? I can't upgrade my OS, my macbook pro is too old.

Please see the attached video if unsure

[running_gps_on_el_capitan.zip](https://github.com/AdaCore/gps/files/3249738/running_gps_on_el_capitan.zip)

**Comment by AnthonyLeonardoGracio** [comment]
Hello Ben,

I am very sorry to hear that. Unfortunately we only support Mac OS Sierra, so we won't be able to help you here... Another thing: GPS won't be supported on Mac OS anymore in the coming year, so the best at this stage would be to download and use GPS from a Linux virtual machine.

Regards,

**Comment by benconvey** [comment]
Hi Anthony. 
Thanks for getting back to me, I'll look into it using parallels for a VM I think. 👍
