### ISSUE TITLE
AttributeError: Tasks_View_Widget instance has no attribute 'timeout'.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#81]
Hello,
Configuration: GPS Community 2019, macOS 10.13.6.
I got this error:
```Traceback (most recent call last):
  File "/adacore/2019/share/gps/support/ui/task_manager.py", line 228, in __destroy
    if self.timeout:
AttributeError: Tasks_View_Widget instance has no attribute 'timeout'
```
Unfortunately it is a random issue when I open a project in GPS.
Maybe more related with big projects which with other projects.
What could be a fix?
HTH, Pascal.

**Comment by ogorodnik** [comment]
It is a known problem and it is being fixed in term of another ticket. So this one I'll close as a duplicate.

But thank you very much for the report.
