### ISSUE TITLE
No compiler specified for "Ada"

### ISSUE THREAD

**Issue by jbrandes** [AdaCore/gps#83]
I am using GPS GNAT and cannot seem to get past this part when I build which is creating a real road block. How do I add an "Ada" compiler? The language is checked off in properties so I know it is there and should be running. 

project test2 is
    for Languages use ("Ada");
    for Source_Dirs use ("src");
    for Object_Dir use "obj";
    for Main use ("main.adb");
end test2;

**Comment by ogorodnik** [comment]
Did you install a compilator? Because GPS is only an IDE and does not contains the compilator inside.

**Comment by jbrandes** [comment]
Can you clarify that? I have it running on GPS GNAT I though that was the compiler.

**Comment by ogorodnik** [comment]
You need to download and install gnat-community-2019-20190517-x86_64-linux-bin and add @install_place@/bin directory to the system PATH variable.
