### ISSUE TITLE
Flash to board

### ISSUE THREAD

**Issue by yago83** [AdaCore/gps#84]
Hi all,
this is my first issue reported for IDE GPS-GNAT.
I have started to learn microcontrollers, and I tried example Text_Scrolling for BBC micro:bit
I had followed instructions, but when I needed to flash to board (I had installed correct 2019-arm-elf), GPS-GNAT raises next error 

`WARNING:pyocd.tools.flash_tool:pyocd-flashtool is deprecated; please use the new combined pyocd tool.
No connected debug probes
Traceback (most recent call last):
  File "/usr/local/bin/pyocd-flashtool", line 10, in <module>
    sys.exit(main())
  File "/home/yago/.local/lib/python2.7/site-packages/pyocd/tools/flash_tool.py", line 160, in main
    with session:
  File "/home/yago/.local/lib/python2.7/site-packages/pyocd/core/session.py", line 284, in __enter__
    assert self._probe is not None
AssertionError
Could not flash the executable.
[workflow stopped]`

I would like to know of it is possible to implement `pyocd tool`

My operating system is Kali 4.17.0-kali3-amd64, I do not know if this could help.

I would like to know how it could be possible to fix it, I had started with Ada.

Thank you in advance

**Comment by ogorodnik** [comment]
Hello @yago83 
We already have a plan to use pyocd directly instead of pyocd-flashtool to avoid this warning, but right now it still should work.

We need some time to investigate how we can help you with the issue you have.
Best regards.
