### ISSUE TITLE
gprbuild issues

### ISSUE THREAD

**Issue by bcartwri96** [AdaCore/gps#88]
Hi there. I'm new here, and while I've been programming in Ada for a couple of years, I don't know how it's compiled etc.

Installing on a new MBP running MacOS Mojave (if it's relevant - though I don't think it should be - I'm using ZSH as my shell), with a freshly installed GNAT / GPS env and SPARK too, I get the following error while trying to compile a file:

```
gprbuild -d -P/Users/bencartwright/...subdirs.../token_ring.gpr -XSpecific_build_modes=Development/Users/bencartwright/...same subs.../token_ring.adb
No valid configuration found
Generation of configuration files failed
GNAT-TEMP-000001.TMP:1:01: "project" expected
gprbuild: processing of configuration project "/private/var/folders/ym/rp9y64qs6gj1f59rvm7szcxh0000gn/T/GNAT-TEMP-000001.TMP" failed
[2019-07-31 23:00:12] process exited with status 4, elapsed time: 00.22s
```

I've tried reinstalling and I've scanned the web for helpful hints, yet none have really helpful (apart from one tangentially related one here on this very repo)

Can someone please help me? Many thanks :)

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

Note that you are on the GPS GitHub repository and this issue relates purely with GPRbuild :)

Could you try to delete the "/private/var/folders/ym/rp9y64qs6gj1f59rvm7szcxh0000gn/T/GNAT-TEMP-000001.TMP" file? If it does not help, you can try to contact our GPRbuild experts on https://github.com/AdaCore/gprbuild

Regards,
