### ISSUE TITLE
Allow expand/hide of Project/Outline area through a simple click

### ISSUE THREAD

**Issue by stcarrez** [AdaCore/gps#89]
This is a suggestion to allow hiding the Project/Outline/Scenario left area easily so that the editor
uses the full window width. I've not found a way to hide temporarily this area (which I need in 95% of cases).

Intelij Idea is doing this for their Project/Outline area and this is very powerful.

- A click on the Project/Outline/Scenario hides it when it is currently displayed,
- A click on another Project/Outline/Scenario switches to the selected item or shows it again.

Having the same behavior would be really nice (and helpful when you switch to different IDEs :-))

**Comment by AnthonyLeonardoGracio** [comment]
Hello Stephane,

GPS can be used in maximized mode by double-clicking on the tab you want to maximize (e.g: the current editor). You just need to double-click on the tab again to unmaximize. Let us know if it fits your needs.

Regards,

**Comment by stcarrez** [comment]
Ok.  Intellj Idea has both: you can maximize the editor by double-clicking the editor tab but you can also hide the project/outline section with a single click. I find the single click more user friendly.

**Comment by AnthonyLeonardoGracio** [comment]
We already have an internal ticket to implement foldable views but it requires a lot of work unfortunately: we have higher priorities for the future, but I hope that we'll find time to implement them one day :)
