### ISSUE TITLE
Not work with Input Method with hints window under GNOME in Fedora

### ISSUE THREAD

**Issue by soiamsoNG** [AdaCore/gps#9]
Test under

GPS Version: GPS 2016 (20160515) hosted on x86_64-pc-linux-gnu
OS: Fedora 25, default GNOME

Input Method with hints window is something like
[https://fedoramagazine.org/master-typing-ibus-booster/](https://fedoramagazine.org/master-typing-ibus-booster/)

I also test the Chinese, Japanese input method, which set similar as above link,  both no hints can show out in GPS.

In the same environment, Gtk.GEntry work with no problem with these input method.

**Comment by setton** [comment]
I guess you could try editing the "gps" wrapper and let GPS run with the system-provided Gtk+, which will probably support this.
