### ISSUE TITLE
Porting an Atollic TrueSTUDIO C project to GPS

### ISSUE THREAD

**Issue by BottCode** [AdaCore/gps#90]
Hi,

I'm porting a **C**  project developed with Atollic TrueStudio for STM32 to Gnat Programming Studio.

In Atollic you can include header files without specifying their actual path, so writing only the file's name.

An example will make this clear.
Suppose you have the following scenario:

    Src/
         main.c
    Inc/
         interface.h

In `main.c` you can include `interface.h` just writing `#include "interface.h"`, without writing `#include "../Inc/interface.h"`.
That's because in Atollic you can specify a set of paths where the compiler will look for the file to include.

For instance, if your path set (in Atollic) is the following
![image](https://user-images.githubusercontent.com/16674092/66665228-6786c300-ec4e-11e9-87b3-34a1175f11a3.png)

the compiler checks if the included file exists in any path

It seems that no similar mechanism exists in GPS, **am I wrong?**
Changing the inclusion of each header file by hand, specifying its path, would be a terrible job.

Hope I've clearly explained my problem.

**Comment by ogorodnik** [comment]
I guess you can find all you need in /Edit/Project properties menu item. In the Properties dialog select Directories item (on the left side). Than you will be able to add directories where source files are (including sub-directories if it is needed).

Hope this will help.

**Comment by BottCode** [comment]
That's exactly what I was looking for. Thanks!
