### ISSUE TITLE
Remote Connections Don't work on Windows

### ISSUE THREAD

**Issue by jsinglet** [AdaCore/gps#94]
After hours of trying things, it seems that remote connections don't work on windows 10.

I set up a plink ssh connection that uses rsync to connect to the remote host. After enabling debugging I get the following: 

```<Timeout> Cannot get a valid prompt. Received so far```

On Linux, this appears to work fine with no troubleshooting. 

Are there any tricks to getting remote development going in GPS? I can attach the debug logs, but after reading them (and executing the commands it logs for myself) everything works fine.

**Comment by ogorodnik** [comment]
Hello,
It is a known issue and we already have it on our wish list.
Right now I would recommend using ssh+Xming on the Windows side to drive GPS which is started on Linux itself.

Best regards,
Andry.
